### ISSUE TITLE
Newlines broken

### ISSUE THREAD

**Issue by nikolask1986** [broadstone-connorbrady/k8s-secret-deployment-generator#1]
For some reason when using this script, newlines appear like

\\n

This needs fixing

**Comment by rexchoppers** [comment]
@nikolask1986 Hi,

Please could you send over an EXAMPLE file (Please do not include any sensitive credentials)

**Comment by rexchoppers** [comment]
Spoken to + issue resolved. JSON files aren't yet supported and debugged what was added into the secrets script. Thanks @nikolask1986
